const datos = [
    {
        id: 1,
        titulo: 'Mi pobre angelito',
        descripcion: 'Un encantador niño de 8 años desafía a un torpe par de ladrones cuando, accidentalmente, sus padres lo olvidan en casa.',
        fecha: '16/11/1990',
        categoria: 'Comedia',
        imagen: require('../assets/img/mipobreangelito.jpg'),
        videoId: '1kSJ6vLDV0c',
    },
    {
        id: 2,
        titulo: 'Shrek',
        descripcion: 'Un ogro llamado Shrek vive en su pantano, pero su preciada soledad se ve súbitamente interrumpida por la invasión de los ruidosos personajes de los cuentos de hadas. Todos fueron expulsados de sus reinos por el malvado Lord Farquaad. Decidido a salvar su hogar, Shrek hace un trato con Farquaad y se prepara para rescatar a la princesa Fiona, quien será la esposa de Farquaad.',
        fecha: '22/04/2001',
        categoria: 'Comedia',
        imagen: require('../assets/img/shrek.jpg'),
        videoId: 'CwXOrWvPBPk',
    },
    {
        id: 3,
        titulo: '¿Y dónde están las rubias?',
        descripcion: 'Dos torpes agentes del FBI se hacen pasar por dos chicas de la alta sociedad para investigar una serie de secuestros. No obstante, mientras preparan su plan, descubren que irrumpir en la clase privilegiada es mucho más duro de lo que creían.',
        fecha: '23/06/2004',
        categoria: 'Comedia',
        imagen: require('../assets/img/rubias.jpg'),
        videoId: 'UxER50XHW-I',
    },
    {
        id: 4,
        titulo: 'Super cool',
        descripcion: 'Seth (Jonah Hill) y Evan (Michael Cera), dos estudiantes co-dependientes de preparatoria, tienen grandes esperanzas en su fiesta de graduación: los jóvenes se sienten retados por la sociedad y planean divertirse en grande y conseguir chicas hermosas para finalmente poder integrarse con sus compañeros.',
        fecha: '17/08/2007',
        categoria: 'Comedia',
        imagen: require('../assets/img/super-cool.jpg'),
        videoId: 'Vfbo361oKYs',
    },
    {
        id: 5,
        titulo: 'Más barato por docena',
        descripcion: 'Mientras su esposa viaja por negocios, un entrenador de fútbol americano tiene que lidiar con el caos que provocan sus 12 hijos.',
        fecha: '25/12/2003',
        categoria: 'Comedia',
        imagen: require('../assets/img/mas-barato-por-docena.jpg'),
        videoId: 'jw2mjK5tdcM',
    },
    {
        id: 6,
        titulo: 'Los Minions',
        descripcion: 'Los minions, ingenuos y torpes, buscan un verdadero villano al que servir. A lo largo de una evolución de millones de años, los minions se han puesto al servicio de los amos más despreciables. Kevin, acompañado por el rebelde Stuart y el adorable Bob, emprende un emocionante viaje para conseguir una jefa a quien servir, la terrible Scarlet Overkill.',
        fecha: '10/07/2015',
        categoria: 'Comedia',
        imagen: require('../assets/img/los-minions.jpg'),
        videoId: '3RyJ127cJR8',
    },
    {
        id: 7,
        titulo: 'After. Almas perdidas',
        descripcion: 'Cuando Tessa toma una decisión trascendental, revelaciones familiares y su pasado amenazan con cambiar sus planes.',
        fecha: '01/09/2021',
        categoria: 'Romance',
        imagen: require('../assets/img/after.jpg'),
        videoId: 's9J8CSM53YU',
    },
    {
        id: 8,
        titulo: 'Corazones malheridos',
        descripcion: 'Cassie y Luke no podrían ser más diferentes. Cassie trabaja en un bar y persigue su sueño de convertirse en cantante. Luke está a punto de embarcarse para el servicio militar. Pero un encuentro casual en el bar de Cassie cambia el curso de sus vidas.',
        fecha: '29/07/2022',
        categoria: 'Romance',
        imagen: require('../assets/img/corazones-malheridos.jpg'),
        videoId: '_fdh6K3gv80',
    },
    {
        id: 9,
        titulo: 'Yo antes de ti',
        descripcion: 'La vida de Louisa Clark, una chica alegre y alocada, que va empalmando un trabajo con otro para ayudar a su familia a subsistir, cambia por completo cuando comienza a trabajar como cuidadora de un joven millonario, quien quedó paralítico tras un accidente. Poco a poco, se va estableciendo entre ellos una conexión cada vez más íntima.',
        fecha: '03/06/2016',
        categoria: 'Romance',
        imagen: require('../assets/img/yo-antes-de-ti.jpg'),
        videoId: 'y-tS4DcM-Ug',
    },
    {
        id: 10,
        titulo: 'Marry Me',
        descripcion: 'Una estrella del pop descubre que su prometido la engaña momentos antes de su gran boda, así que decide casarse con un completo desconocido del público, sin darse cuenta de que sus vidas, quizá, van a quedar unidas para siempre.',
        fecha: '11/02/2022',
        categoria: 'Romance',
        imagen: require('../assets/img/marry-me.jpg'),
        videoId: '8hXboMXWavE',
    },
    {
        id: 11,
        titulo: 'Todo, todo',
        descripcion: 'Maddy, una adolescente enferma, pero imaginativa e inteligente, vive confinada en casa porque si sale de ella podría morir. Maddy se enamora de Olly, su vecino, aunque los muchachos sólo pueden relacionarse a través de la ventana y enviándose mensajes de texto; tan fuerte se vuelve su vínculo que Maddy se plantea arriesgarse a morir con tal de poder sentir cerca a Olly.',
        fecha: '19/05/2017',
        categoria: 'Romance',
        imagen: require('../assets/img/todo-todo.jpg'),
        videoId: 'nbTAvoWH7_c',
    },
    {
        id: 12,
        titulo: 'Bajo la misma estrella',
        descripcion: 'Dos adolescentes pacientes de cáncer inician un viaje para reafirmar sus vidas y visitar a un escritor solitario en Ámsterdam.',
        fecha: '06/06/2014',
        categoria: 'Romance',
        imagen: require('../assets/img/bajo-la-misma-estrella.jpg'),
        videoId: '9Lt8QAZkc94',
    },
    {
        id: 13,
        titulo: 'Black Widow',
        descripcion: 'Una peligrosa conspiración, relacionada con su pasado, persigue a Natasha Romanoff, también conocida como Viuda Negra. La agente tendrá que lidiar con las consecuencias de haber sido espía, así como con las relaciones rotas, para sobrevivir.',
        fecha: '09/07/2021',
        categoria: 'Acción',
        imagen: require('../assets/img/black-widow.jpg'),
        videoId: 'HV0f9FCd8KY',
    },
    {
        id: 14,
        titulo: 'El justiciero',
        descripcion: 'Robert McCall, un antiguo comando de operaciones especiales que ha fingido su propia muerte, se ve obligado a salir de su retiro para salvar la vida de Teri, una joven que se encuentra en manos de unos mafiosos rusos ultraviolentos.',
        fecha: '26/09/2014',
        categoria: 'Acción',
        imagen: require('../assets/img/el-justiciero.jpg'),
        videoId: 'rlMaxFG7blg',
    },
    {
        id: 15,
        titulo: 'El justiciero 2',
        descripcion: 'Unos criminales asesinan a Susan Plummer, la mejor amiga y antigua compañera de trabajo de Robert McCall. A partir de ese momento, en la mente de Robert solo hay una obsesión: eliminar a la banda de asesinos de élite que ha destrozado su vida.',
        fecha: '20/07/2018',
        categoria: 'Acción',
        imagen: require('../assets/img/el-justiciero-2.jpg'),
        videoId: 'VEabO-7462s',
    },
    {
        id: 16,
        titulo: 'Hombre en llamas',
        descripcion: 'Contratado como guardaespaldas de una niña, un agente retirado de la CIA se venga de sus secuestradores en México.',
        fecha: '21/04/2004',
        categoria: 'Acción',
        imagen: require('../assets/img/hombre-en-llamas.jpg'),
        videoId: 'CKXoyArIoO8',
    },
    {
        id: 17,
        titulo: 'Rambo Acorralado',
        descripcion: 'El veterano de Vietnam, John Rambo, envuelve a la policía en una cacería en el bosque tras escapar de un vil comisario.',
        fecha: '22/10/1982',
        categoria: 'Acción',
        imagen: require('../assets/img/rambo.jpg'),
        videoId: '-dzmAS_B1Qw',
    },
    {
        id: 18,
        titulo: 'Rápido y furioso: reto Tokio',
        descripcion: 'Sean Boswell siempre se ha sentido como un intruso, pero él se define a sí mismo a través de sus victorias como corredor callejero de autos. Su pasatiempo lo vuelve impopular con las autoridades, así que se va a vivir con su padre a Japón. Una vez allá, y aún más enajenado, Sean descubre un nuevo deporte emocionante, pero peligroso. Las apuestas son muy altas cuando Sean se enfrenta al campeón local y se enamora de su novia.',
        fecha: '16/06/2006',
        categoria: 'Acción',
        imagen: require('../assets/img/reto-tokyo.jpg'),
        videoId: 'p8HQ2JLlc4E',
    },
    {
        id: 19,
        titulo: 'Capitán América: el primer vengador',
        descripcion: 'Tras tres meses de someterse a un programa de entrenamiento físico y táctico, encomiendan a Steve Rogers su primera misión como Capitán América. Armado con un escudo indestructible, emprende la guerra contra la perversa organización HYDRA.',
        fecha: '19/07/2011',
        categoria: 'Acción',
        imagen: require('../assets/img/capitan-america.jpg'),
        videoId: '8-gP9CkRpCA',
    },
    {
        id: 20,
        titulo: 'Avengers: Endgame',
        descripcion: 'Los Vengadores restantes deben encontrar una manera de recuperar a sus aliados para un enfrentamiento épico con Thanos, el malvado que diezmó el planeta y el universo.',
        fecha: '26/04/2019',
        categoria: 'Acción',
        imagen: require('../assets/img/endgame.jpg'),
        videoId: 'siQ8_HTzNaM',
    }
];

export default datos;